FROM python:3.11-slim

WORKDIR /code

RUN apt-get update && apt-get -y install \
    ffmpeg \
    libsndfile1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -f https://download.pytorch.org/whl/cpu/torch_stable.html torch==2.2.2
RUN pip install --no-cache-dir -r requirements.txt

COPY preprocessing/ /code/preprocessing/
COPY models/ /code/models/
COPY main.py /code/main.py

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
